version: '3'
services:
  aikopanel:
    # build: 
    #   context: .
    image: aikocute/aikopanel:latest
    volumes:
      - ./:/www/
      # - ./.env:/www/.env
      - redis-socket:/run/redis-socket # Gắn ổ cắm
    environment:
      - docker=true #Được sử dụng để xác định xem đó có phải là môi trường docker cho tập lệnh cài đặt không
    depends_on:
      - redis
    network_mode: host #Sử dụng chế độ máy chủ theo mặc định, bạn cần chế độ cầu để tự nhận xét
    restart: always
    # ports:
    #   - 7001:7001
  redis:
    build: 
      context: .docker/services/redis
    restart: always
    volumes:
      - ./.docker/.data/redis:/data/ # Gắn dữ liệu dai dẳng redis
      - redis-socket:/run/redis-socket # Gắn ổ cắm
volumes:
  redis-socket: